Improved readability for promotion messages
Lautenschlager-id/ModuloBot pull request #2
Opened 2019-12-10 11:44 UTC by Seniru

Changed the message (which is displayed when someone get promoted) to a more readable format 

The changes can be summarized as follows

```diff
- Seniru is now a(n) `DEVELOPER`.

@@Changes into@@

+ Seniru is now a DEVELOPER.
+ Seniru is now an ARTIST.

```

2019-12-10 11:45 UTC, Seniru commented
The current implementation of this is a one-liner without less readability (in the code i mean). The readability can be improved by creating a separate function. I want to know where to inserst the new function. Thanks 👍

2019-12-10 16:44 UTC, Lautenschlager-id requested changes

2019-12-10 16:44 UTC, Lautenschlager-id commented on bot.lua
> +									description = "**" .. member.name .. "** is now " .. ((not not string.match(string.upper(role.name)), '^[AEIOU]')) and ' an ' or ' a ' ) .. `" .. string.upper(role.name) .. "`.",
We don't use string.match for this kind of situation.
```suggestion
									description = "**" .. member.name .. "** is now " .. (string.find(role.name, "^[AEIOUaeiou]") and "a" or "an") .. " `" .. string.upper(role.name) .. "`.",
```

2019-12-11 07:46 UTC, Seniru commented
I applied your suggestion to my code.

2019-12-14 00:42 UTC, Lautenschlager-id approved these changes

2019-12-14 00:42 UTC, merged

2019-12-14 03:30 UTC, Seniru commented
Thanks 👍